# Generated by Django 4.2.7 on 2024-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='id',
        ),
        migrations.AddField(
            model_name='cursos',
            name='id_curso',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id_estudiante',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='materias',
            name='id_materia',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='cantidadEstudiantes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
