# Generated by Django 4.2.7 on 2024-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_remove_cursos_id_remove_estudiantes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id_curso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='id_estudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materias',
            name='id_materia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
