# Generated by Django 4.2.7 on 2024-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_alter_cursos_id_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('estudiante_id', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=50)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='id_estudiante',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='cursos',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='materias',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
