# Generated by Django 5.0.7 on 2024-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0004_alter_category_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completado',
        ),
    ]
